---
title: "Project 4 - Example Main Script"
author: "Jing Wu, Tian Zheng"
date: "3/22/2017"
output:
  html_document: default
  pdf_document: default
---

## Step 0: Load the packages, specify directories and commands

```{r}
#if (!require("pacman")) install.packages("pacman")
#pacman::p_load(text2vec, dplyr, qlcMatrix, kernlab, knitr)

```

Commands:

```{r}
#Read raw data files
read.movie.data = F
read.ms.data = F

#Reshape data to wide format
reshape.movie = F
reshape.ms = F

#Load Rdata
load.movie.data = F
load.ms.data = T

#Implementation algorythims
model.clustering = T
cross.validate.model.clustering = T
```

## Step 1: Load and process the data

Read Movie Dataset:

```{r}
if (read.movie.data){

  #Read dataset from directory
  movie.data.train <- read.csv("../data/movie_data_train.csv")
  movie.data.test <- read.csv("../data/movie_data_test.csv")
  
  movie.data.train <- movie.data.train[,-1]
  movie.data.test <- movie.data.test[,-1]
  
  #Check dataset information
  paste("Data Dimension:", dim(movie.data.train)[1], "x", dim(movie.data.train)[2])
  paste("Number of Unique Movies:",length(unique(movie.data.train[,2])))
  paste("Number of Unique Users:",length(unique(movie.data.train[,3])))
  paste("Number of 0 ratings:", sum(movie.data.train[,4] == 1))

}
```

Read ms Dataset:

```{r}
if (read.ms.data){

  #Read dataset from directory
  ms.data.train <- read.csv("../data/ms_data_train.csv")
  ms.data.test <- read.csv("../data/ms_data_test.csv")
  
  ms.data.train <- ms.data.train[,-1]
  ms.data.test <- ms.data.test[,-1]
  
  #Reshapes TRAIN dataframe -------------------------------------------
  User <- rep(NA, nrow(ms.data.train))
  
  for(i in 1:nrow(ms.data.train)){
    User[i] <- ifelse(ms.data.train[i,1] == "C", ms.data.train[i,3], User[i-1])
  }
  ms.data.train$User <- User
  ms.data.train <- ms.data.train[ms.data.train$V1 == "V",]
  ms.data.train <- ms.data.train[,-1]
  
  names(ms.data.train) <- c("Vroot", "Visits", "User")
  
  #Reshapes TEST dataframe -------------------------------------------
  User <- rep(NA, nrow(ms.data.test))
  
  for(i in 1:nrow(ms.data.test)){
    User[i] <- ifelse(ms.data.test[i,1] == "C", ms.data.test[i,3], User[i-1])
  }
  ms.data.test$User <- User
  ms.data.test <- ms.data.test[ms.data.test$V1 == "V",]
  ms.data.test <- ms.data.test[,-1]
  
  names(ms.data.test) <- c("Vroot", "Visits", "User")
  
  #Clean
  rm(User, i)
}
```

Reshape and save movie data:

```{r}
if(reshape.movie){

  #Reshapes dataframe
  movie.data.train <- reshape(movie.data.train, 
                              v.names = "Score", 
                              direction = "wide", 
                              idvar = "User", 
                              timevar = "Movie")
  
   movie.data.test <- reshape(movie.data.test, 
                              v.names = "Score", 
                              direction = "wide", 
                              idvar = "User", 
                              timevar = "Movie") 
  
  
  
  paste("Data Dimension:", dim(movie.data.train)[1], "x", dim(movie.data.train)[2])
  paste("Data Dimension:", dim(movie.data.test)[1], "x", dim(movie.data.test)[2])
  
  #Save files to data directory
  save(movie.data.train, file = "../data/movie_data_train_wide.Rdata")
  save(movie.data.test, file = "../data/movie_data_test_wide.Rdata")
  }
```

Reshape and save ms data:

```{r}
if(reshape.ms){

  #Reshapes dataframe
  ms.data.train <- reshape(ms.data.train, 
                              v.names = "Visits", 
                              direction = "wide", 
                              idvar = "User", 
                              timevar = "Vroot")
  
   ms.data.test <- reshape(ms.data.test, 
                              v.names = "Visits", 
                              direction = "wide", 
                              idvar = "User", 
                              timevar = "Vroot") 
  
  
  
  paste("Data Dimension:", dim(ms.data.train)[1], "x", dim(ms.data.train)[2])
  paste("Data Dimension:", dim(ms.data.test)[1], "x", dim(ms.data.test)[2])
  
  #Save files to data directory
  save(ms.data.train, file = "../data/ms_data_train_wide.Rdata")
  save(ms.data.test, file = "../data/ms_data_test_wide.Rdata")
  }
```


## Step 2: Implementation

Load Data:

```{r}
#Load Rdata files
if(load.movie.data){
  load("../data/movie_data_train_wide.Rdata")
  load("../data/movie_data_test_wide.Rdata")
}

if(load.ms.data){
  load("../data/ms_data_train_wide.Rdata")
  load("../data/ms_data_test_wide.Rdata")
}
```

Implement Clustering Model:

```{r}
#Training function
cluster.model.train <- function(data.set, C = 3, replace.na = T, tau = 0.1, max.iter = 12){
  
    #Debbuging-------
    #C = 3
    #data.set = ms.data.train
    #replace.na = T
    #tau = 0.1
    #max.iter = 20
  
    #Set-Up------------------------------------------------
    if(replace.na){
      data.set[is.na(data.set)] <- 0
    }
  
    user <- data.set[,1]
    data.set <- data.set[,-1]
    
    websites <- names(data.set)
    k <- sort(unique(unlist(c(data.set[,-1]))))
    N <- nrow(data.set)
    
    #Step 1------------------------------------------------
    u <- runif(C)
    mu <- u/sum(u)
    
    lambda <- array(NA, dim = c(length(k), ncol(data.set), C))
    
    for(ce in 1:C){
      u <- runif(ncol(data.set))
      u2 <- 1 - u
      
      lambda[1,,ce] <- u
      lambda[2,,ce] <- u2
    }
    
    rm(u, u2)
    
    pi <- matrix(NA, nrow = N, ncol = C)
    pi.old <- matrix(0, nrow = N, ncol = C)
    phi <- matrix(NA, nrow = N, ncol = C)
    D <- matrix(NA, nrow = N, ncol = (length(k)))
    iteration <- 1
    d <- Inf
    #------------------------------------------------------
    
  while(d[length(d)] > tau & iteration < max.iter){
      
    #Step 2------------------------------------------------
    
    for(i in 1:N){
      
      aux <- rep(0, C)
      
      for(j in 1:ncol(data.set)) {
        
        aux <- aux + log(lambda[ data.set[i,j] + 1, j, ]) 
      }
      
      phi[i, ] <- exp(aux)
    }
    
    num <- mu * phi
    den <- apply(num, 1, sum)   
  
    pi <- num/den
    #------------------------------------------------------
    
    #Step 3------------------------------------------------
    
    mu <- apply(pi, 2, sum)/N
    
    for(ce in 1:C){
    
      for(j in 1:ncol(data.set)){
        
      l <- t(pi[, ce]) %*% ifelse(data.set[, j] == 1, 1, 0)
        
      lambda[2, j, ce] <- l/sum(pi[ ,ce])
      lambda[1, j, ce] <- 1 - lambda[2, j, ce] 
        
      }
    }
    
    d <- c(d, norm(pi - pi.old))
    
    pi.old <- pi
    
    iteration <- iteration + 1
    
    print(paste("Iteration:", iteration, "norm d:", d[length(d)]))
  }
    
  return(list("pi" = pi, "lambda" = lambda, "mu" = mu, "iterations" = iteration, 
              "progression" = d, "websites" = websites, "user_list" = user))
}  

#Testing function
cluster.model.test <- function(data.set.test, lambda, mu, pi, websites, replace.na = T, alpha = 5){
  
  #Debugging
  #data.set.test <- ms.data.test
  
  #SetUp-----------------------------------------------------------------
  if(replace.na){
    data.set.test[is.na(data.set.test)] <- 0
  }
  
  user <- data.set.test[,1]
  data.set.test <- data.set.test[,-1]
    
  websites.test <- names(data.set.test)
  websites.test.index <- match(websites.test, websites)
  
  N <- nrow(data.set.test)
  predictions <- as.data.frame(matrix(NA, nrow = N, ncol = ncol(data.set.test)))
  names(predictions) <- websites.test
  #-----------------------------------------------------------------------
  
  #Assign users to cluster and make prediction------------------------------------------------
    
  user.cluster <- apply(pi, 1, which.max)
  
  for(i in 1:N){
    for(j in 1:ncol(predictions)){
      
      cluster <- user.cluster[i]
      index <- websites.test.index[j]
      predictions[i,j] <- as.numeric(which.max(lambda[, index, cluster]) - 1)    

    }
  }
  
  #------------------------------------------------------
  
  #Rank scoring------------------------------------------
  
  d <- 0 #Neutral vote
  C <- c(dim(lambda)[3])
  
  lambda.minor <- lambda[, websites.test.index,]
  recommendations <- matrix(NA, nrow = C, ncol = alpha)
  votes <- matrix(NA, nrow = C, ncol = alpha)
  
  for(ce in 1:C){
    recommendations[ce,] <- order(lambda.minor[,,ce][2,], decreasing = T)[1:alpha]
    a <- recommendations[ce,]
    votes[ce,] <- (lambda.minor[,,ce][2,])[a]
  }
  rm(a)
  
  votes[votes >= 0.5] <- 1
  votes[votes < 0.5] <- 0
  
  ra <- matrix(NA, nrow = nrow(predictions), ncol = 2)
  names(ra) <- c("Ra", "Ra.max")
  
  for(i in 1:nrow(predictions)){
    
    cluster <- user.cluster[i] 
    jay <- 1:alpha
    ra[i,1] <- sum(apply(data.set.test[i, recommendations[cluster,]], 2, max, 0)/(2^((jay-1)/(alpha-1))))  
    
    a <- min(sum(data.set.test[i,]), alpha)
    jay2 <- 1:a
    ra[i,2] <- sum(rep(1, a)/(2^((jay2-1)/(alpha-1))))
  }
  
  R <- round(100 * sum(ra[,1])/sum(ra[,2]), 2)
  print(paste("Rank score:", R))
  #------------------------------------------------------
  
  return(list("predictions" = predictions, "R" = R))
}

```

## Step 3: Evaluation

Test Cluster Model:

```{r}
if(model.clustering){
  best.C <- 2
  
  if(cross.validate.model.clustering){
    r <- c()
    parameters <- c(2,4,6)
    for(par in parameters){
      trained.cluster.model <- cluster.model.train(ms.data.train, C = par)
      
        l <- trained.cluster.model$lambda
        m <- trained.cluster.model$mu
        p <- trained.cluster.model$pi
        w <- trained.cluster.model$websites
       
        testing <- cluster.model.test(ms.data.test, lambda = l, mu = m, pi = p, websites = w, alpha = 7)
        r <- c(r, testing$R)
        print(paste("For number of clusters equal to:", par, "Rank score:", testing$R))
    }
    
    t <- matrix(NA, ncol = length(parameters), nrow = 2)
    t[1,] <- parameters 
    t[2,] <- r
    save(t, file = "../output/cv_cluster_rank_score.Rdata")
    write.csv(t, file = "../output/cv_cluster_rank_score.csv")
    
    print(t)
    best.C <- which.max(r) + 1
    best.C
  }
  

  trained.cluster.model <- cluster.model.train(ms.data.train, C = best.C)
  
  l <- trained.cluster.model$lambda
  m <- trained.cluster.model$mu
  p <- trained.cluster.model$pi
  w <- trained.cluster.model$websites
  
  testing <- cluster.model.test(ms.data.test, lambda = l, mu = m, pi = p, websites = w, alpha = 7)
  
  
  rm(l, m, p, w)
  
  save(trained.cluster.model, file = "../output/trained_cluster_model.Rdata")
}
```







