import pandas as pd
import numpy as np
from copy import deepcopy
from multiprocessing import Pool

df = pd.read_csv('movie_train.csv')
# df = pd.read_csv('ms_train.csv')
df = df.fillna(0)
df = df.set_index('Unnamed: 0', drop = True)

# define s and c matrix, s is the raw score, c is 1 if value exists, 0 else.
s = deepcopy(df)
c = df

c[c>0] = 1

def MSD(i, j):
    num = 0
    dem = 0 
    for n in range(s.shape[1]):
        num += c.iloc[i, n]*c.iloc[j,n]*(s.iloc[i, n]-s.iloc[j, n])**2
        dem += c.iloc[i, n]*c.iloc[j,n]
    return(num/dem)

def calc_MSD(part):
    # part is the starting point of the iteration. chunk is the chunk size, so each worker
    # will work on a chunk size of 50.
    chunk = 50
    start = part
    if ((part + chunk) > s.shape[0]):
        finish = s.shape[0]
    else:
        finish = part+chunk
        
    # we create a D matrix for each worker
    D = [[0 for i in range(s.shape[0])] for i in range(finish-start)]        
    for x, i in enumerate(range(start, finish, 1)):
        for y, j in enumerate(range(s.shape[0])):
            D[x][y] = MSD(i, j)
    return(D)

p = Pool(64)
# a is a list of matrices generated by each worker in the pool
a = p.map(calc_MSD, list(range(0, s.shape[0], 50)))

# flatten our a and put into one big matrix, then write to csv.
output = pd.DataFrame([item for sublist in a for item in sublist])
output.columns = list(df.index)
output.index = list(df.index)
output.to_csv('MSDsim_movie.csv')
# output.to_csv('MSDsim_ms.csv')
