---
title: "Selecting Neighbors"
author: "Yijia Li"
date: "11/27/2017"
output: html_document
---

# load similarity matrix
```{r}
#load("/Users/yijiali/Desktop/movie_data_train_wide.Rdata")
matrix1<- read.csv("../data/MSDsim_movie.csv")
userid<-matrix1$X[1:1000]
rownames(matrix1)<- matrix1$X
matrix1$X<-c()
matrix1<-matrix1[1:1000,1:1000]
matrix_new<-as.matrix(matrix1)

#userid<-movie.data.train$User[1:50]
#rownames(matrix1)<- movie.data.train$User[1:50]
#matrix1$X<-c()
#colnames(matrix1)<-movie.data.train$User[1:50]
```

# correlation_threshold function
```{r}
correlation_threshold <- function(threshold){
  for(i in 1:nrow(matrix_new)) {
    for(j in 1:ncol(matrix_new)) {
      if (is.na(matrix_new[i,j])==FALSE) {
        if(matrix_new[i,j]<=threshold) {
          matrix_new[i,j]<-substring(colnames(matrix_new)[j], 2)
          #matrix_new[i,j]<-colnames(matrix_new)[j]
        } else {
          matrix_new[i,j]<-NA
        }
      }
    }
  }
  return(matrix_new)
}
```

# set threshold=1
```{r}
method_1<-correlation_threshold(1)
method_1 <- cbind(userid, method_1)
write.csv(method_1, file='../output/method_1_MSD.csv', row.names = FALSE)
```

# load similarity matrix
```{r}
matrix2<- read.csv("../output/usersim.csv")
userid<-matrix2$users
rownames(matrix2)<- matrix2$users
matrix2$users<-c()
matrix_new<-as.matrix(matrix2)
```

# best_n_neighbors function
```{r}
best_n_neighbors <- function(n){
  for(i in 1:nrow(matrix_new)) {
      a <- sort(matrix_new[i,],decreasing = TRUE)[n]
    for(j in 1:ncol(matrix_new)) {
       if (is.na(matrix_new[i,j])==FALSE && is.na(a)==FALSE) {
         if(matrix_new[i,j]>=a) {
            matrix_new[i,j]<-substring(colnames(matrix_new)[j], 2)
            #matrix_new[i,j]<-colnames(matrix_new)[j]
         } else{
            matrix_new[i,j]<-NA
         }
       }
    }
  }
  return(matrix_new)
}
```

# set n=20
```{r}
#use this for sample
method_2<-best_n_neighbors(20)
#use this for real matrix
#best_n_neighbors(20)
method_2 <- cbind(userid, method_2)
write.csv(method_2, file='../output/method_2_SR.csv', row.names = FALSE)
```

# combined function
```{r}
combined <- function(threshold,n){
  for(i in 1:nrow(matrix_new)) {
    a <- sort(matrix_new[i,],decreasing = TRUE)[n]
    for(j in 1:ncol(matrix_new)) {
      if (is.na(matrix_new[i,j])==FALSE && is.na(a)==FALSE) {
        if(matrix_new[i,j]>=a && matrix_new[i,j]>=threshold) {
          matrix_new[i,j]<-substring(colnames(matrix_new)[j], 2)
          #matrix_new[i,j]<-colnames(matrix_new)[j]
        } else{
          matrix_new[i,j]<-NA
        }
      }
    }
  }
  return(matrix_new)
}
```

# set threshold=0.05,n=20
```{r}
#use this for sample
method_3<-combined(0.05,20)
#use this for real matrix
#combined(0.1,20)
method_3 <- cbind(userid, method_3)
write.csv(method_3, file='../output/method_3_SR.csv', row.names = FALSE)
```

# load similarity matrix
```{r}
matrix4<- read.csv("../output/users_cosine.csv")
userid<-matrix4$userid
rownames(matrix4)<- matrix4$userid
matrix4$userid<-c()
matrix_new<-as.matrix(matrix4)
```

# best_n_neighbors function
```{r}
best_n_neighbors <- function(n){
  for(i in 1:nrow(matrix_new)) {
      a <- sort(matrix_new[i,],decreasing = TRUE)[n]
    for(j in 1:ncol(matrix_new)) {
       if (is.na(matrix_new[i,j])==FALSE && is.na(a)==FALSE) {
         if(matrix_new[i,j]>=a) {
            matrix_new[i,j]<-substring(colnames(matrix_new)[j], 2)
            #matrix_new[i,j]<-colnames(matrix_new)[j]
         } else{
            matrix_new[i,j]<-NA
         }
       }
    }
  }
  return(matrix_new)
}
```

# set n=20
```{r}
#use this for sample
method_2<-best_n_neighbors(20)
#use this for real matrix
#best_n_neighbors(20)
method_2 <- cbind(userid, method_2)
write.csv(method_2, file='../output/method_2_Cosine.csv', row.names = FALSE)
```

